name: 'Write .env'
description: 'Writes .env file for the project to access relevant variables'

inputs:
  vars:
    description: 'Vars as JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: echo "DATABASE_URI=${{ inputs.vars.DATABASE_URI }}\n" > .env

    - shell: bash
      run: echo "PAYLOAD_PUBLIC_SERVER_URL=${{ inputs.vars.PAYLOAD_PUBLIC_SERVER_URL }}\n" >> .env

    - shell: bash
      run: cat .env
