name: 'Write .env'
description: 'Writes .env file for the project to access relevant variables'

inputs:
  vars:
    description: 'Vars as JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: cat .env

    - shell: bash
      run: echo "DATABASE_URI=${{ fromJSON(inputs.vars).DATABASE_URI }}" > .env

    - shell: bash
      run: echo "PAYLOAD_PUBLIC_SERVER_URL=${{ fromJSON(inputs.vars).PAYLOAD_PUBLIC_SERVER_URL }}" >> .env

    - shell: bash
      run: cat .env
