# This workflow builds and pushes a Docker container to Google Artifact Registry and deploys it to Cloud Run.
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Whitelist Github Actions worker IP to MongoDB Atlas
# 4. Build a docker container
# 5. Remote the whitelisted IP from MongoDB Atlas
# 6. Publish the Docker image to Google Artifact Registry
# 7. Deploy it to Cloud Run

name: 'Deploy to GCP'
description: 'Builds and pushes a Docker container to Google Artifact Registry and deploys it to Cloud Run'

inputs:
  environment:
    description: 'Deployment environment'
    required: true
  gcp-project-id:
    description: 'Google Cloud Platform Project ID'
    required: true
  gcp-service-account:
    description: 'Google Cloud Platform Service Account used for deployments'
    required: true
  gcp-workload-identity-provider:
    description: 'Google Cloud Platform Workload Identity Provider name'
    required: true
  gar-location:
    description: 'Google Artifact Registry location'
    required: true
  gar-repository:
    description: 'Google Artifact Registry repository name'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: access_token
        project_id: '${{ inputs.gcp-project-id }}'
        workload_identity_provider: '${{ inputs.gcp-workload-identity-provider }}'
        service_account: '${{ inputs.gcp-service-account }}'

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v3'
      with:
        registry: ${{ inputs.gar-location }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    

    - name: Build and Push Container
      shell: bash
      run: |-
        docker build -t "${{ inputs.gar-location }}-docker.pkg.dev/${{ inputs.gcp-project-id }}/${{ inputs.gar-repository }}/${{ inputs.gcp-project-id }}-${{ inputs.environment }}:${{ github.sha }}" ./
        docker push "${{ inputs.gar-location }}-docker.pkg.dev/${{ inputs.gcp-project-id }}/${{ inputs.gar-repository }}/${{ inputs.gcp-project-id }}-${{ inputs.environment }}:${{ github.sha }}"
