name: Deploy to development

on:
  push:
    branches: [develop, feature/*]

jobs:
  deploy:
    environment: development
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Write .env'
        uses: './.github/workflows/_write-env'
        with:
          vars: ${{ toJson(vars) }}
          secrets: ${{ toJson(secrets) }}

      - name: 'Deploy'
        uses: './.github/workflows/_deploy'
        with:
          environment: 'development'
          gcp-project-id: ${{ vars.GCP_PROJECT_ID }}
          gcp-service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          gcp-workload-identity-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gar-location: ${{ vars.GAR_LOCATION }}
          gar-repository: ${{ vars.GAR_REPOSITORY }}
          mongodb-atlas-public-api-key: ${{ vars.MONGODB_ATLAS_PUBLIC_API_KEY }}
          mongodb-atlas-private-api-key: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          mongodb-atlas-org-id: ${{ vars.MONGODB_ATLAS_ORG_ID }}
          mongodb-atlas-project-id: ${{ vars.MONGODB_ATLAS_PROJECT_ID }}
